//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.DirectoryServices.Protocols {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.DirectoryServices.Protocols.Resources.Strings", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is invalid base-64-encoded data..
        /// </summary>
        internal static string BadBase64Value {
            get {
                return ResourceManager.GetString("BadBase64Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid DSML control..
        /// </summary>
        internal static string BadControl {
            get {
                return ResourceManager.GetString("BadControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an unknown result code &quot;{0}&quot;..
        /// </summary>
        internal static string BadOperationResponseResultCode {
            get {
                return ResourceManager.GetString("BadOperationResponseResultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP filter string is invalid..
        /// </summary>
        internal static string BadSearchLDAPFilter {
            get {
                return ResourceManager.GetString("BadSearchLDAPFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the BER conversion..
        /// </summary>
        internal static string BerConversionError {
            get {
                return ResourceManager.GetString("BerConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;format&quot; string argument and the passed in &quot;value&quot; argument do not match..
        /// </summary>
        internal static string BerConverterNotMatch {
            get {
                return ResourceManager.GetString("BerConverterNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;format&quot; string contains an invalid character..
        /// </summary>
        internal static string BerConverterUndefineChar {
            get {
                return ResourceManager.GetString("BerConverterUndefineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback function can not be null when partial result processing is in ReturnPartialResultsAndNotifyCallback mode..
        /// </summary>
        internal static string CallBackIsNull {
            get {
                return ResourceManager.GetString("CallBackIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast concurrent bind is only supported on Windows 2003 and later operating systems..
        /// </summary>
        internal static string ConcurrentBindNotSupport {
            get {
                return ResourceManager.GetString("ConcurrentBindNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection cannot contain a null DirectoryControl object..
        /// </summary>
        internal static string ContainNullControl {
            get {
                return ResourceManager.GetString("ContainNullControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP server returned an unknown error..
        /// </summary>
        internal static string DefaultLdapError {
            get {
                return ResourceManager.GetString("DefaultLdapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified operation error occurred..
        /// </summary>
        internal static string DefaultOperationsError {
            get {
                return ResourceManager.GetString("DefaultOperationsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DirectoryAttribute value can only be converted between byte array and string..
        /// </summary>
        internal static string DirectoryAttributeConversion {
            get {
                return ResourceManager.GetString("DirectoryAttributeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.DirectoryServices.Protocols is not supported on this platform..
        /// </summary>
        internal static string DirectoryServicesProtocols_PlatformNotSupported {
            get {
                return ResourceManager.GetString("DirectoryServicesProtocols_PlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdapConnection object does not support DsmlAuthRequest..
        /// </summary>
        internal static string DsmlAuthRequestNotSupported {
            get {
                return ResourceManager.GetString("DsmlAuthRequestNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI that is supplied must be either &quot;http&quot; or &quot;https&quot;..
        /// </summary>
        internal static string DsmlNonHttpUri {
            get {
                return ResourceManager.GetString("DsmlNonHttpUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ErrorResponse DSML element was returned..
        /// </summary>
        internal static string ErrorResponse {
            get {
                return ResourceManager.GetString("ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error response contains an invalid type attribute &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorResponseInvalidValue {
            get {
                return ResourceManager.GetString("ErrorResponseInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The async result is invalid..
        /// </summary>
        internal static string InvalidAsyncResult {
            get {
                return ResourceManager.GetString("InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name and password must be null when the authentication type is anonymous..
        /// </summary>
        internal static string InvalidAuthCredential {
            get {
                return ResourceManager.GetString("InvalidAuthCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientCertificates can contain only zero or one certificate..
        /// </summary>
        internal static string InvalidClientCertificates {
            get {
                return ResourceManager.GetString("InvalidClientCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DSML document could not be parsed..
        /// </summary>
        internal static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter type &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string InvalidFilterType {
            get {
                return ResourceManager.GetString("InvalidFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP connection only accepts SearchRequest objects that have string type filters..
        /// </summary>
        internal static string InvalidLdapSearchRequestFilter {
            get {
                return ResourceManager.GetString("InvalidLdapSearchRequestFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified parameter should be a &quot;{0}&quot; type..
        /// </summary>
        internal static string InvalidValueType {
            get {
                return ResourceManager.GetString("InvalidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified request is not supported..
        /// </summary>
        internal static string InvliadRequestType {
            get {
                return ResourceManager.GetString("InvliadRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administration limit on the server was exceeded..
        /// </summary>
        internal static string LDAP_ADMIN_LIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("LDAP_ADMIN_LIMIT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple directory service agents are affected..
        /// </summary>
        internal static string LDAP_AFFECTS_MULTIPLE_DSAS {
            get {
                return ResourceManager.GetString("LDAP_AFFECTS_MULTIPLE_DSAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when dereferencing the alias..
        /// </summary>
        internal static string LDAP_ALIAS_DEREF_PROBLEM {
            get {
                return ResourceManager.GetString("LDAP_ALIAS_DEREF_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alias is invalid..
        /// </summary>
        internal static string LDAP_ALIAS_PROBLEM {
            get {
                return ResourceManager.GetString("LDAP_ALIAS_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object exists..
        /// </summary>
        internal static string LDAP_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("LDAP_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute exists or the value has been assigned..
        /// </summary>
        internal static string LDAP_ATTRIBUTE_OR_VALUE_EXISTS {
            get {
                return ResourceManager.GetString("LDAP_ATTRIBUTE_OR_VALUE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication method is not supported..
        /// </summary>
        internal static string LDAP_AUTH_METHOD_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("LDAP_AUTH_METHOD_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown authentication error occurred..
        /// </summary>
        internal static string LDAP_AUTH_UNKNOWN {
            get {
                return ResourceManager.GetString("LDAP_AUTH_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is busy..
        /// </summary>
        internal static string LDAP_BUSY {
            get {
                return ResourceManager.GetString("LDAP_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client loop was detected..
        /// </summary>
        internal static string LDAP_CLIENT_LOOP {
            get {
                return ResourceManager.GetString("LDAP_CLIENT_LOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute and known values do not match..
        /// </summary>
        internal static string LDAP_COMPARE_FALSE {
            get {
                return ResourceManager.GetString("LDAP_COMPARE_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute and known values match..
        /// </summary>
        internal static string LDAP_COMPARE_TRUE {
            get {
                return ResourceManager.GetString("LDAP_COMPARE_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality is required for this operation..
        /// </summary>
        internal static string LDAP_CONFIDENTIALITY_REQUIRED {
            get {
                return ResourceManager.GetString("LDAP_CONFIDENTIALITY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection cannot be established. .
        /// </summary>
        internal static string LDAP_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("LDAP_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value in the request is invalid..
        /// </summary>
        internal static string LDAP_CONSTRAINT_VIOLATION {
            get {
                return ResourceManager.GetString("LDAP_CONSTRAINT_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified control was not found. .
        /// </summary>
        internal static string LDAP_CONTROL_NOT_FOUND {
            get {
                return ResourceManager.GetString("LDAP_CONTROL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decoding error occurred..
        /// </summary>
        internal static string LDAP_DECODING_ERROR {
            get {
                return ResourceManager.GetString("LDAP_DECODING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An encoding error occurred..
        /// </summary>
        internal static string LDAP_ENCODING_ERROR {
            get {
                return ResourceManager.GetString("LDAP_ENCODING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search filter is invalid..
        /// </summary>
        internal static string LDAP_FILTER_ERROR {
            get {
                return ResourceManager.GetString("LDAP_FILTER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication that was provided was not appropriate..
        /// </summary>
        internal static string LDAP_INAPPROPRIATE_AUTH {
            get {
                return ResourceManager.GetString("LDAP_INAPPROPRIATE_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The matching rule does not apply to the specified attribute type..
        /// </summary>
        internal static string LDAP_INAPPROPRIATE_MATCHING {
            get {
                return ResourceManager.GetString("LDAP_INAPPROPRIATE_MATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has insufficient access rights..
        /// </summary>
        internal static string LDAP_INSUFFICIENT_RIGHTS {
            get {
                return ResourceManager.GetString("LDAP_INSUFFICIENT_RIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied credential is invalid..
        /// </summary>
        internal static string LDAP_INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("LDAP_INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distinguished name contains invalid syntax..
        /// </summary>
        internal static string LDAP_INVALID_DN_SYNTAX {
            get {
                return ResourceManager.GetString("LDAP_INVALID_DN_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The syntax is invalid..
        /// </summary>
        internal static string LDAP_INVALID_SYNTAX {
            get {
                return ResourceManager.GetString("LDAP_INVALID_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is a leaf..
        /// </summary>
        internal static string LDAP_IS_LEAF {
            get {
                return ResourceManager.GetString("LDAP_IS_LEAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A local error occurred..
        /// </summary>
        internal static string LDAP_LOCAL_ERROR {
            get {
                return ResourceManager.GetString("LDAP_LOCAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chain of referrals has looped back to a referring server..
        /// </summary>
        internal static string LDAP_LOOP_DETECT {
            get {
                return ResourceManager.GetString("LDAP_LOOP_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More results will be returned..
        /// </summary>
        internal static string LDAP_MORE_RESULTS_TO_RETURN {
            get {
                return ResourceManager.GetString("LDAP_MORE_RESULTS_TO_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A naming violation occurred..
        /// </summary>
        internal static string LDAP_NAMING_VIOLATION {
            get {
                return ResourceManager.GetString("LDAP_NAMING_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough memory to perform the task..
        /// </summary>
        internal static string LDAP_NO_MEMORY {
            get {
                return ResourceManager.GetString("LDAP_NO_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is attempting to modify an object class that cannot be modified..
        /// </summary>
        internal static string LDAP_NO_OBJECT_CLASS_MODS {
            get {
                return ResourceManager.GetString("LDAP_NO_OBJECT_CLASS_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were returned. .
        /// </summary>
        internal static string LDAP_NO_RESULTS_RETURNED {
            get {
                return ResourceManager.GetString("LDAP_NO_RESULTS_RETURNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested attribute does not exist..
        /// </summary>
        internal static string LDAP_NO_SUCH_ATTRIBUTE {
            get {
                return ResourceManager.GetString("LDAP_NO_SUCH_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object does not exist..
        /// </summary>
        internal static string LDAP_NO_SUCH_OBJECT {
            get {
                return ResourceManager.GetString("LDAP_NO_SUCH_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed on a non-leaf object..
        /// </summary>
        internal static string LDAP_NOT_ALLOWED_ON_NONLEAF {
            get {
                return ResourceManager.GetString("LDAP_NOT_ALLOWED_ON_NONLEAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed on a relative distinguished name..
        /// </summary>
        internal static string LDAP_NOT_ALLOWED_ON_RDN {
            get {
                return ResourceManager.GetString("LDAP_NOT_ALLOWED_ON_RDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is not supported. .
        /// </summary>
        internal static string LDAP_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("LDAP_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object class violation occurred..
        /// </summary>
        internal static string LDAP_OBJECT_CLASS_VIOLATION {
            get {
                return ResourceManager.GetString("LDAP_OBJECT_CLASS_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search results exceed the specified offset range..
        /// </summary>
        internal static string LDAP_OFFSET_RANGE_ERROR {
            get {
                return ResourceManager.GetString("LDAP_OFFSET_RANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operation error occurred..
        /// </summary>
        internal static string LDAP_OPERATIONS_ERROR {
            get {
                return ResourceManager.GetString("LDAP_OPERATIONS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        internal static string LDAP_OTHER {
            get {
                return ResourceManager.GetString("LDAP_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bad parameter was passed to a routine..
        /// </summary>
        internal static string LDAP_PARAM_ERROR {
            get {
                return ResourceManager.GetString("LDAP_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only partial results and referrals were received..
        /// </summary>
        internal static string LDAP_PARTIAL_RESULTS {
            get {
                return ResourceManager.GetString("LDAP_PARTIAL_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A protocol error occurred..
        /// </summary>
        internal static string LDAP_PROTOCOL_ERROR {
            get {
                return ResourceManager.GetString("LDAP_PROTOCOL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A referral was returned from the server..
        /// </summary>
        internal static string LDAP_REFERRAL {
            get {
                return ResourceManager.GetString("LDAP_REFERRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referral limit has been exceeded..
        /// </summary>
        internal static string LDAP_REFERRAL_LIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("LDAP_REFERRAL_LIMIT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned results are too large..
        /// </summary>
        internal static string LDAP_RESULTS_TOO_LARGE {
            get {
                return ResourceManager.GetString("LDAP_RESULTS_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A SASL bind is in progress..
        /// </summary>
        internal static string LDAP_SASL_BIND_IN_PROGRESS {
            get {
                return ResourceManager.GetString("LDAP_SASL_BIND_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was aborted because the send timeout limit was exceeded..
        /// </summary>
        internal static string LDAP_SEND_TIMEOUT {
            get {
                return ResourceManager.GetString("LDAP_SEND_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP server is unavailable..
        /// </summary>
        internal static string LDAP_SERVER_DOWN {
            get {
                return ResourceManager.GetString("LDAP_SERVER_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size limit was exceeded.
        /// </summary>
        internal static string LDAP_SIZELIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("LDAP_SIZELIMIT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search requires a SORT control..
        /// </summary>
        internal static string LDAP_SORT_CONTROL_MISSING {
            get {
                return ResourceManager.GetString("LDAP_SORT_CONTROL_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong authentication is required for this operation..
        /// </summary>
        internal static string LDAP_STRONG_AUTH_REQUIRED {
            get {
                return ResourceManager.GetString("LDAP_STRONG_AUTH_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call completed successfully..
        /// </summary>
        internal static string LDAP_SUCCESS {
            get {
                return ResourceManager.GetString("LDAP_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time limit set by the server-side time limit parameter was exceeded..
        /// </summary>
        internal static string LDAP_TIMELIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("LDAP_TIMELIMIT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was aborted because the client side timeout limit was exceeded. .
        /// </summary>
        internal static string LDAP_TIMEOUT {
            get {
                return ResourceManager.GetString("LDAP_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is unavailable..
        /// </summary>
        internal static string LDAP_UNAVAILABLE {
            get {
                return ResourceManager.GetString("LDAP_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server does not support the control. The control is critical..
        /// </summary>
        internal static string LDAP_UNAVAILABLE_CRIT_EXTENSION {
            get {
                return ResourceManager.GetString("LDAP_UNAVAILABLE_CRIT_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is not defined..
        /// </summary>
        internal static string LDAP_UNDEFINED_TYPE {
            get {
                return ResourceManager.GetString("LDAP_UNDEFINED_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cannot handle directory requests..
        /// </summary>
        internal static string LDAP_UNWILLING_TO_PERFORM {
            get {
                return ResourceManager.GetString("LDAP_UNWILLING_TO_PERFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user cancelled the operation..
        /// </summary>
        internal static string LDAP_USER_CANCELLED {
            get {
                return ResourceManager.GetString("LDAP_USER_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when attempting to perform a requested Virtual List View operation. .
        /// </summary>
        internal static string LDAP_VIRTUAL_LIST_VIEW_ERROR {
            get {
                return ResourceManager.GetString("LDAP_VIRTUAL_LIST_VIEW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error response is missing the type attribute..
        /// </summary>
        internal static string MissingErrorResponseType {
            get {
                return ResourceManager.GetString("MissingErrorResponseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation response is missing the result code..
        /// </summary>
        internal static string MissingOperationResponseResultCode {
            get {
                return ResourceManager.GetString("MissingOperationResponseResultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server failed to return a DirectoryResponse..
        /// </summary>
        internal static string MissingResponse {
            get {
                return ResourceManager.GetString("MissingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search result is missing the attribute name..
        /// </summary>
        internal static string MissingSearchResultEntryAttributeName {
            get {
                return ResourceManager.GetString("MissingSearchResultEntryAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distinguished name is missing in the SearchResultEntry of the search response..
        /// </summary>
        internal static string MissingSearchResultEntryDN {
            get {
                return ResourceManager.GetString("MissingSearchResultEntryDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server failed to return a session identifier..
        /// </summary>
        internal static string MissingSessionId {
            get {
                return ResourceManager.GetString("MissingSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active session exists for this connection..
        /// </summary>
        internal static string NoCurrentSession {
            get {
                return ResourceManager.GetString("NoCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-CLSCompliant exception is thrown..
        /// </summary>
        internal static string NonCLSException {
            get {
                return ResourceManager.GetString("NonCLSException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative value is not permitted for the size limit..
        /// </summary>
        internal static string NoNegativeSizeLimit {
            get {
                return ResourceManager.GetString("NoNegativeSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A negative value is not permitted for the time limit..
        /// </summary>
        internal static string NoNegativeTimeLimit {
            get {
                return ResourceManager.GetString("NoNegativeTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP connection cannot retrieve a partial result set..
        /// </summary>
        internal static string NoPartialResults {
            get {
                return ResourceManager.GetString("NoPartialResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server failed to return a session identifier..
        /// </summary>
        internal static string NoSessionIDReturned {
            get {
                return ResourceManager.GetString("NoSessionIDReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is not the return value from BeginSendRequest..
        /// </summary>
        internal static string NotReturnedAsyncResult {
            get {
                return ResourceManager.GetString("NotReturnedAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is not supported on a DsmlErrorResponse..
        /// </summary>
        internal static string NotSupportOnDsmlErrRes {
            get {
                return ResourceManager.GetString("NotSupportOnDsmlErrRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response from the server is not a well-formed DSML document..
        /// </summary>
        internal static string NotWellFormedResponse {
            get {
                return ResourceManager.GetString("NotWellFormedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null reference cannot be added to DirectoryAttribute or DirectoryAttributeModification objects. .
        /// </summary>
        internal static string NullDirectoryAttribute {
            get {
                return ResourceManager.GetString("NullDirectoryAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A null reference cannot be added to DirectoryAttributeCollection or DirectoryAttributeModificationCollection objects. .
        /// </summary>
        internal static string NullDirectoryAttributeCollection {
            get {
                return ResourceManager.GetString("NullDirectoryAttributeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array should not contain null reference..
        /// </summary>
        internal static string NullValueArray {
            get {
                return ResourceManager.GetString("NullValueArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval of partial results set is supported only by the SearchRequest object..
        /// </summary>
        internal static string PartialResultsNotSupported {
            get {
                return ResourceManager.GetString("PartialResultsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document is read-only..
        /// </summary>
        internal static string ReadOnlyDocument {
            get {
                return ResourceManager.GetString("ReadOnlyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property is read-only..
        /// </summary>
        internal static string ReadOnlyProperty {
            get {
                return ResourceManager.GetString("ReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active session already exists for this connection..
        /// </summary>
        internal static string SessionInUse {
            get {
                return ResourceManager.GetString("SessionInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value exceeds the maximum allowed..
        /// </summary>
        internal static string TimespanExceedMax {
            get {
                return ResourceManager.GetString("TimespanExceedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport layer security is not supported on Windows 2000..
        /// </summary>
        internal static string TLSNotSupported {
            get {
                return ResourceManager.GetString("TLSNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Stop TLS operation failed..
        /// </summary>
        internal static string TLSStopFailure {
            get {
                return ResourceManager.GetString("TLSStopFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an unknown response element..
        /// </summary>
        internal static string UnknownResponseElement {
            get {
                return ResourceManager.GetString("UnknownResponseElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;value&quot; parameter must be a string or byte[] type..
        /// </summary>
        internal static string ValidDirectoryAttributeType {
            get {
                return ResourceManager.GetString("ValidDirectoryAttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;filter&quot; parameter must be a string or DsmlDocument type..
        /// </summary>
        internal static string ValidFilterType {
            get {
                return ResourceManager.GetString("ValidFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than or equal to 0..
        /// </summary>
        internal static string ValidValue {
            get {
                return ResourceManager.GetString("ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;values&quot; parameter must be a string[], byte[][], or Uri[] type..
        /// </summary>
        internal static string ValidValuesType {
            get {
                return ResourceManager.GetString("ValidValuesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a string, byte[], or Uri type..
        /// </summary>
        internal static string ValidValueType {
            get {
                return ResourceManager.GetString("ValidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server names cannot contain a space character..
        /// </summary>
        internal static string WhiteSpaceServerName {
            get {
                return ResourceManager.GetString("WhiteSpaceServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assertion is null and is invalid for the compare operation..
        /// </summary>
        internal static string WrongAssertionCompare {
            get {
                return ResourceManager.GetString("WrongAssertionCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DsmlSoapHttpConnection does not support &quot;{0}&quot; authentication type..
        /// </summary>
        internal static string WrongAuthType {
            get {
                return ResourceManager.GetString("WrongAuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one value can be specified for the compare operation..
        /// </summary>
        internal static string WrongNumValuesCompare {
            get {
                return ResourceManager.GetString("WrongNumValuesCompare", resourceCulture);
            }
        }
    }
}
